parameters:
#    pointage.example.class: Digital\PointageBundle\Example

services:
#    pointage.example:
#        class: %pointage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
